### ISSUE TITLE
TypeError when running

### ISSUE THREAD

**Issue by KennthShang** [WeiliWw/VirHostMatcher-Net#13]
Hi,

I got a TypeError when running the software, do you have any idea how to solve it?
![image](https://user-images.githubusercontent.com/22445402/128840912-cc393b83-3262-4992-af83-b4f379f3adc6.png)

**Comment by WeiliWw** [comment]
Could you provide the command and data you used?

**Comment by KennthShang** [comment]
The command is: `python VirHostMatcher-Net.py -q input/ --short-contig -o output -t 8`
An example of the data is in the attachment
[contig.zip](https://github.com/WeiliWw/VirHostMatcher-Net/files/6980000/contig.zip)

**Comment by KennthShang** [comment]
Hi, it seems all the data and pre-feature cannot be downloaded. The webpage is inaccessible. Do you have any idea?

**Comment by WeiliWw** [comment]
Thanks for providing the data! There is actually a bug when no CRISPR match is found for any query genomes. It's fixed in today's [commit](https://github.com/WeiliWw/VirHostMatcher-Net/commit/2eac0f84ea96a5e81111e162ffabf5a0448c50ef).

For the webpage issue, let me contact the service team in the school. If the service is deprecated, I will try to put the data somewhere else. Will update this thread by the end of this week.

**Comment by KennthShang** [comment]
Good to know! Thanks a lot

**Comment by WeiliWw** [comment]
Hi, I updated the download links - please let me know if there are any issues. Thanks!
