### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by felipehcoutinho** [WeiliWw/VirHostMatcher-Net#7]
Hi, first I would like to congratulate you and your team on putting together this amazing tool. 

I ran on some issues when installing it from git with the specified commands. I ran:

`git clone https://github.com/WeiliWw/VirHostMatcher-Net.git
rohit@flamingo:~/felipe$ cd VirHostMatcher-Net/
CC=g++ python setup.py install --install-platlib=./src/`

And received the following errors:

> running install
running build
running build_ext
building 'tools' extension
g++ -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/rohit/.local/lib/python2.7/site-packages/numpy/core/include -I./src/tools/ -I/usr/include/python2.7 -c ./src/tools/tools.cpp -o build/temp.linux-x86_64-2.7/./src/tools/tools.o -w -std=c++11
./src/tools/tools.cpp:55:27: error: variable ‘PyModuleDef toolsmodule’ has initializer but incomplete type
 static struct PyModuleDef toolsmodule = {
                           ^
./src/tools/tools.cpp:56:5: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
     PyModuleDef_HEAD_INIT,
     ^
./src/tools/tools.cpp: In function ‘void PyInit_tools()’:
./src/tools/tools.cpp:67:40: error: ‘PyModule_Create’ was not declared in this scope
     return PyModule_Create(&toolsmodule);
                                        ^
./src/tools/tools.cpp:67:40: error: return-statement with a value, in function returning 'void' [-fpermissive]
error: command 'g++' failed with exit status 1

Below are my system specs:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                144
On-line CPU(s) list:   0-143
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               2600.730
CPU max MHz:           2301,0000
CPU min MHz:           1000,0000
BogoMIPS:              4602.37
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-17,72-89
NUMA node1 CPU(s):     18-35,90-107
NUMA node2 CPU(s):     36-53,108-125
NUMA node3 CPU(s):     54-71,126-143

And the output of pip freeze:

adium-theme-ubuntu==0.3.4
asn1crypto==0.24.0
awscli==1.15.4
backports.lzma==0.0.3
bcbio-gff==0.6.4
beautifulsoup4==4.4.1
biolib==0.0.46
biom-format==2.1.7
biopython==1.66
botocore==1.10.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
checkm-genome==1.0.11
Click==7.0
colorama==0.3.7
comparem==0.0.23
crcmod==1.7
cryptography==2.1.4
cssselect==0.9.1
cvxopt==1.1.4
cycler==0.10.0
decorator==4.0.6
DendroPy==4.3.0
docutils==0.14
enum34==1.1.6
ete2==2.3.10
flye==2.7b0
future==0.16.0
futures==3.2.0
gmpy==1.17
gtdbtk==0.1.3
h5py==2.8.0
helperlibs==0.1.9
html5lib==0.999
HTSeq==0.12.4
humann2==2.8.1
idna==2.6
ipaddress==1.0.19
ipython==2.4.1
jdcal==1.0
Jinja2==2.8
jmespath==0.9.3
joblib==0.9.4
kraken-biom==1.0.1
lxml==3.5.0
MarkupSafe==0.23
matplotlib==1.5.3
mercurial==4.7.2
mpld3==0.3
mpmath==0.19
ncbi-genome-download==0.2.5
networkx==1.11
nose==1.3.7
numexpr==2.4.3
numpy==1.16.6
openpyxl==2.3.0
pandas==0.23.4
patsy==0.4.1
pexpect==4.0.1
Pillow==3.1.2
Pmw==1.3.2
ptyprocess==0.5
py==1.4.31
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0
pyExcelerator==0.6.4.1
pyglet==1.1.4
pymol==1.7.2.1
PyMySQL==0.7.2
pyOpenSSL==17.5.0
pyparsing==2.0.3
pyqi==0.3.2
pyquery==1.2.9
pysam==0.16.0.1
Pyste==0.9.10
pysvg==0.2.2
pytest==2.8.7
python-dateutil==2.6.1
pytz==2014.10
PyYAML==3.12
pyzmq==15.2.0
reportlab==3.3.0
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.13
scikit-learn==0.17
scipy==0.17.0
simplegeneric==0.8.1
simplejson==3.8.1
six==1.11.0
statsmodels==0.6.1
sympy==0.7.6.1
tables==3.2.2
tornado==4.2.1
tqdm==4.43.0
unity-lens-photos==1.0
urllib3==1.22
vboxapi==1.0
virtualenv==15.0.1
WebOb==1.5.1
xlrd==0.9.4
xlwt==0.7.5

Regards,

Felipe

**Comment by WeiliWw** [comment]
Hi Felipe,

Thanks for sharing the error info! Seems you are using Python2. However, we need Python3.4+ to work with our software. Please check the *Dependencies* in README for details. 

Best,
Weili

**Comment by WXYWD** [comment]
Hi, I have some trouble when I run the pymol.Could you please help me sovle it? Thanks.
$ pymol
<string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted

**Comment by WeiliWw** [comment]
Seems this pymol command is not related to our software.
